export const SET_BOARD_STATE = 'SET_BOARD_STATE';

export const SET_GAME_MODE = 'SET_GAME_MODE';

export const SET_PLAYER1 = 'SET_PLAYER1';
export const SET_PLAYER2 = 'SET_PLAYER2';
export const SET_CURRENT_PLAYER = 'SET_CURRENT_PLAYER';

export const SET_SELECTED_PIECE = 'SET_SELECTED_PIECE';

export const SET_SELECTED_PIECE_MOVES = 'SET_SELECTED_PIECE_MOVES';
export const RESET_SELECTED_PIECE_MOVES = 'RESET_SELECTED_PIECE_MOVES';

export const SET_WINNER = 'SET_WINNER';

export const INIT_GAME = 'INIT_GAME';
export const RESET_GAME = 'RESET_GAME';

